### ISSUE TITLE
How to save/restore saved model

### ISSUE THREAD

**Issue by 123mitnik** [nivwusquorum/tensorflow-deepq#12]
how to save and later resume training after restoring already trained model

Thank You !

**Comment by siemanko** [comment]
Check out the tensorflow variable saving tutorial.

Essentially you need to create saver object

``` python
saver = tf.train.saver()
```

then you can save and restore variables like this (i hope i got the order of arguments right...):

``` python
saver.save(session, 'saved_model')
saver.restore(session, 'saved_model')
```

**Comment by 123mitnik** [comment]
Thank You for the ultrafast and helpful response !
