### ISSUE TITLE
Discrete Hill python notebook

### ISSUE THREAD

**Issue by davikrehalt** [nivwusquorum/tensorflow-deepq#16]
I can't seem to replicate your results in the game notebook. Is your ipython notebook output for that outdated? or is there something subtle going on? I simply ran your game python notebook, but it doesn't seem to learn at all. I haven't seriously studied your code, so some help is appreciated in debugging

**Comment by siemanko** [comment]
Hi David,

I am sorry I commit that example by mistake, it is not supported :( I did it long time ago and I do not remember what it was doing. Sorry I could not be more helpful.

Szymon
