### ISSUE TITLE
TF version, circular import dependencies, AttributeError: 'module' object has no attribute 'ops

### ISSUE THREAD

**Issue by meppe** [nivwusquorum/tensorflow-deepq#18]
Hi, 

I have a problem with executing the Karpathy game notebook. Cell 9 gives rise to the following error:

```
---------------------------------------------------------------------------AttributeError                            Traceback (most recent call last)<ipython-input-6-16dd03e0e8b6> in <module>()
      6 else:
      7     # Tensorflow business - it is always good to reset a graph before creating a new controller.
----> 8     tf.ops.reset_default_graph()
      9     session = tf.InteractiveSession()
     10 
AttributeError: 'module' object has no attribute 'ops

```

This usually happens when there are circular import dependencies, however, I could not find any. I am using Tensorflow 0.71 and Python 2.7.6 The error also occurs with Python 3.4. Which Python and tensorflow version are you using? 

Thanks a lot for the nice code!

**Comment by siemanko** [comment]
I am using tensorflow 0.6 and python 3.4.

But if just this one line changed, maybe it's worth looking up what the equivalent in tf 0.7

**Comment by meppe** [comment]
I did look it up, 
`tf.ops.reset_default_graph()`
is the same in tf 0.71, so that should not be the problem.

**Comment by siemanko** [comment]
yeah, apparently it changed. It lost an `ops`.

``` python3
tf.reset_default_graph()
```

**Comment by meppe** [comment]
Great, that fixed it! Thanks a lot! It runs fine with PyCharm now. I have another issue when I run this  with Jupyter in a browser, but that''s a different story.
