### ISSUE TITLE
Performance decrease after recent commits

### ISSUE THREAD

**Issue by stas-sl** [nivwusquorum/tensorflow-deepq#2]
Hi! Thanks for useful examples of tensorflow usage.

I'm playing with Deep Q-Learning example and noticed that after some of recent commits performance of DiscreteDeepQ dropped ~5x times. I'm wondering what caused it? Is it because of maintaining 2 copies of q-network? Is there an option to update weights less frequently? Sorry, I don't understand what is going on there very well yet.

**Comment by stas-sl** [comment]
I also noticed excessive memory usage which didn't happen before.

**Comment by siemanko** [comment]
Yeah, I notice that as well. Maintaining two separate copies of the network is critical for the deep q performance, so I really want to keep it, but I am not sure what causes the leak. I will keep looking. Let me know if you find anything.

One possible thing to investigate is logging. (try passing summary writter=None

**Comment by siemanko** [comment]
Fixed in 0d848e5d73fb21f63405592b69b167f300c6265a

**Comment by stas-sl** [comment]
Thanks! 

So the issue was caused by SummaryWriter and not by having 2 q-networks. That's good to know ) Though, graphs were beautiful ) Do you think it's a TF issue?

**Comment by siemanko** [comment]
Nah, check out the closing commit. The issue was the fact that I create multiple tf.no_op() operations (one every training step). Apparently that's really bad. I was extremely surprised. But I guess there's some logic to it...

**Comment by stas-sl** [comment]
Aaah... I saw it, but you set `calculate_summaries = False` as well, so I thought that was the main reason. Now I enabled summary and see that it works as fast as before - that's great!
Agree that there could be logic - if you create thousands instances of new nodes, even if they are exact the same, it can very wasteful, if not cached somehow internally in TF.
