### ISSUE TITLE
How long training for this game?

### ISSUE THREAD

**Issue by dsetiady** [nivwusquorum/tensorflow-deepq#21]
Hi,

I wonder, how long training taking time so that the ai agent can act like your gif on this github page?

Thanks,

**Comment by siemanko** [comment]
About 5 minutes. (make sure fast mode is active).

**Comment by dsetiady** [comment]
Well, its fast enough. How about training epoch? How many epoch need so that AI agent can be smart to make a decision?

**Comment by siemanko** [comment]
I never counted.

Rough estimate:

150 FPS \* 5 MINUTES \* 60 S = 45 000 epochs.

Each epoch consist of 32 element minibatch sampled from experience replay.
