### ISSUE TITLE
where does the tensorflow model gets saved

### ISSUE THREAD

**Issue by kumarsameer** [nivwusquorum/tensorflow-deepq#22]
I tried to figure out tf.train.Saver or something similar in the code, but couldn't locate it. So, where does the model ( *.ckpt )  gets saved ?
I can write my own saver, but since there is saved model for karpathy game already, I was wondering if I am missing something ?

**Comment by siemanko** [comment]
In this notebook:

https://github.com/nivwusquorum/tensorflow-deepq/blob/master/notebooks/karpathy_game.ipynb

Create a saver:

``` python
saver = tf.train.Saver(brain.variables())
saver.restore(session, "path/to/saved/model")
```
