### ISSUE TITLE
i don't understand how to use this

### ISSUE THREAD

**Issue by eightys3v3n** [nivwusquorum/tensorflow-deepq#25]
I'm so sorry to be asking this.
I tried for an hour and I can't figure out how to use or run it. Could someone please give me a pointer towards the right direction? I got as far as moving it into the site-packages directory of python, I am running a redis server even though I have no idea how to use it, and I think I have all the modules installed. I really would like to play around with this and experiment with different games but I would rather not start from scratch until I'm sure this is what I want to learn.

**Comment by eightys3v3n** [comment]
i shouldn't have asked; ignore this issue. sorry again.

**Comment by JohnAllen** [comment]
Did you get it working?

**Comment by eightys3v3n** [comment]
No, do you mind providing me with some more detailed instructions on
running the game on the readme? Once I can run that I think I can reverse
engineer the rest to figure out how to use it.

**Comment by JohnAllen** [comment]
You had a redis server running?

**Comment by eightys3v3n** [comment]
yes I installed it and started the service. I didn't see any "getting started" configuration pages on the website so I assumed it would work without any configuration.
I saw that it was required somewhere in the readme so I ran it just in case.

**Comment by JohnAllen** [comment]
There's a file in the repo somewhere where I think you can just `python somefile.py` and it should run a simulator and write images somewhere.  I'm not at my machine with these deps instsalled so I will look later tonight.  Try and find that file and run it and post what the output is.

**Comment by eightys3v3n** [comment]
tf_rl/simulate.py? it outputs nothing and creates no images.

**Comment by eightys3v3n** [comment]
I have to leave for today; I'll check back later.

**Comment by siemanko** [comment]
Hi eightys3v3n,

The example running code is in the karpathy game ipython3 notebook. Check it out.

Szymon

**Comment by eightys3v3n** [comment]
i don't know how to use ipython. i don't think explaining this is worth your time. i've gotten distracted with another project and may not loop back around to this project for a while. Thank you for your help so far!

**Comment by eightys3v3n** [comment]
i'm sorry to waste some of your time

**Comment by flobotics** [comment]
hi, i cloned your repo and run "ipython3 notebooks/karpathy_game.ipynb" on ubuntu 14.04, but the result is:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/usr/lib/python3/dist-packages/IPython/utils/py3compat.py in execfile(fname, glob, loc)
     98         loc = loc if (loc is not None) else glob
     99         with open(fname, 'rb') as f:
--> 100             exec(compile(f.read(), fname, 'exec'), glob, loc)
    101 
    102     # Refactor print statements in doctests.

/home/ros/git-repos/tensorflow-deepq/notebooks/karpathy_game.ipynb in <module>()
      5    "execution_count": 1,
      6    "metadata": {
----> 7     "collapsed": false
      8    },
      9    "outputs": [],

NameError: name 'false' is not defined
```

**Comment by siemanko** [comment]
Wow, this is such a poetic error. Correct way to use ipython notebooks. Is typing `ipython3 notebook` in the notebooks folder and the rest happens in your browser.

**Comment by flobotics** [comment]
thanks @nivwusquorum for your help. After starting "ipython3 notebook" a web-page opened and i clicked on karpathy_game.ipynb and then "Cell->Run all" it returned errors and i changed in cell 6 
- tf.ops.reset_default_graph() to  tf.reset_default_graph()

and then firstly changed but then out-commeted the line
- #journalist.add_graph(session.graph())

the error is, what you have written as a comment above this code-block "graph was not available when journalist was created "
but now i got a new error:

`Exception AssertionError: AssertionError() in <bound method InteractiveSession.__del__ of <tensorflow.python.client.session.InteractiveSession object at 0x7f6df86829d0>> ignored`

The graphic is working, but the reward is only -0.0 or 0.0 ?

**Comment by siemanko** [comment]
Can you try and see if pulling the newest version helps? Repo was updated yesterday

**Comment by flobotics** [comment]
i did a git pull and it updated some files and it directly runs, but the reward in the graphic is only -0.0 or 0.0 ?

**Comment by siemanko** [comment]
Hi flobotics, I'd like to help you, but I need a bit more to go on. Can you give me a more detailed description of the issue, or perhaps a video? 

Also just a wild guess, but try running once cell at the time, now all at once. In particular don't run any of the cells below the simulation.

**Comment by flobotics** [comment]
i was running "Cell->Run all", now i did it like you said "Cell->Run Cells and Select below" (hope this is what you meant?), but the reward is -0.0 or 0.0.   I made a video to better show it, here [video](https://www.youtube.com/watch?v=VOueuUH2LTo)

**Comment by siemanko** [comment]
Ahh... I see what you mean. The reward represents instantaneous reward collected in the last step. If you disable `fast_mode` then you might see minor variations. Most importantly though, as the training progresses you should see the total number of collected green marbles to be much higher than red marbles. This way you will know the network is training.

btw. you can use shift+enter to run a notebook cell, so that you can do less clicking ;-)

**Comment by flobotics** [comment]
i set fast_mode = False but the reward stays the same, it never gets incremented or decremented ?
The training seemed to progress, as you said, it eats more friends than enemies.
