### ISSUE TITLE
it always stuck at ...

### ISSUE THREAD

**Issue by SeekPoint** [nivwusquorum/tensorflow-deepq#26]
envy@ub1404:~/os_pri/github/tensorflow-deepq$ python3 tf_rl/controller/human_controller.py
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally

**Comment by siemanko** [comment]
you should try running the notebook instead (karpathy game is recommended)
