### ISSUE TITLE
Add more drawing options

### ISSUE THREAD

**Issue by lsqshr** [nivwusquorum/tensorflow-deepq#31]
In `simulate(...)`, it assumes the environment is drawn with svg strings. However it might not generalise to complex game environment. For example, im drawing in 3D at the moment and it is easy to use matplotlib (maybe pyopengl in the future?). 

Is it possible to make the environment drawing interface more general? My thought is something like

```
...
simulation.setup_draw() # Initialise figure handles, axes for reuse
...

for frame_no ...
    ...
    simulation.draw() # Draw things by plot, scatter, etc or Ipython display()
    ...
```

In this way, all the figure handles and drawing stuff are handled by the environment class, e.g. KarparthyGame

Pls let me know if you like this idea. If so, I can make another pull request and see how it goes

**Comment by siemanko** [comment]
Absolutely, I will gladly accept your pool request as long as it is backwards compatible. In particular would it require changes to KarpathyGame class? 

I can imagine getting the best of both worlds by doing something like:

``` python
if hasattr(simulation, 'setup_draw'):
    simulation.setup_draw()
```

This way KarpathyGame class doesn't need to change.

**Comment by lsqshr** [comment]
That's great! I will try to make a pull request and see how it goes.
