### ISSUE TITLE
add LICENSE file

### ISSUE THREAD

**Issue by kerokeroloid** [nivwusquorum/tensorflow-deepq#7]
Hi! what's the license this is released under?

**Comment by siemanko** [comment]
MIT. Out of curiosity are you planning any deep q learning based project? :-)

**Comment by kerokeroloid** [comment]
I'm trying to make agents learn chess without any supervision, just playing against each other. The "trick" I want to try is to instantiate a lot (10, 100, 1000? not sure how many is practical) networks, and make them play randomly against each other, to force them to make their strategy more general. I'm calling it BOB (bunch-of-brains learning) :)

I'm 99.9% sure it won't work but it might be fun to try! :)

If this fails, I'm going to try end to end agar.io playing from pixels with a convnet :)

... and that's going to fail too haha. I'm just toying with deep learning as a hobby.

EDIT: wow, that was a lot of smileys.

**Comment by siemanko** [comment]
Sounds like a cool idea.

One thing you might want to consider is to keep the number of networks constant say (N=40) and periodically kill N/2 weakest performers and replace them with initially starting ones. This way you will keep the number of networks and games that you need to play low (those things are already pretty slow).

Now, that I think about it you could actually do full blown evolutionary programming - mutate and crossover the winning networks. I believe it could be pretty cool! I have some more ideas for it, let me know if you're interested we can chat about it.

**Comment by kerokeroloid** [comment]
chatting about it would be really cool. Let me know how. Keep in mind that I don't have much theoretical background, again, just a hobby.

**Comment by siemanko** [comment]
Just message me on gchat ( szymon.sidor@gmail.com ).
